### PR TITLE
feat: method to set clientId and clientSecret

### PR DESCRIPTION
**Pull request by Sorikairox**

### CODE REVIEW

**Comment by boywithkeyboard** [comment]
@Sorikairox why would you want this?

**Comment by boywithkeyboard** [comment]
A different approach would be to make `Preset` an abstract class and the individual providers extend it and let the options be passed through the constructor.

**Comment by Sorikairox** [comment]
So, similarly to oauth2_client, I would like to instanciate the oauth client once by passing everything necessary, and use them.
In this file, you can see how it's done:
https://github.com/Savory/saaskit-danet/blob/main/back/src/auth/oauth2/service.ts

I have a map of clients, to easily access a client with its provider name: 

```ts
this.clients.set(
      'google',
      new OAuth2Client({
        clientId: Deno.env.get('GOOGLE_CLIENT_ID')!,
        clientSecret: Deno.env.get('GOOGLE_CLIENT_SECRET')!,
        authorizationEndpointUri: 'https://accounts.google.com/o/oauth2/auth',
        tokenUri: 'https://accounts.google.com/o/oauth2/token',
        redirectUri: `${Deno.env.get('HOSTNAME')}/oauth2/callback`,
        defaults: {
          scope: [
            'https://www.googleapis.com/auth/userinfo.email',
            'https://www.googleapis.com/auth/userinfo.profile',
          ],
        },
      }),
    );


this.clients.get('google');
```


The suggestion of having an abstract class is a good one, but that would be a breaking change.

**Comment by boywithkeyboard** [comment]
Closed with #3

**Pull request closed without merging**
